

###get all Post
GET http://localhost:3000/articles HTTP/1.1
###get Post with id given
GET http://localhost:3000/articles/1 HTTP/1.1

###add a Post
POST http://localhost:3000/articles HTTP/1.1

{
    "title": "What is DevOps",
    "content": "DevOps is a software development methodology that aims to integrate development  and operations teams to improve the speed  and quality of software delivery."
}

###delete a Post with id given
DELETE http://localhost:3000/articles/3 HTTP/1.1
###modify Post 
PATCH http://localhost:3000/articles HTTP/1.1
Content-Type: application/json

{
    "id":4,
    "title":"Cyber security",
    "content":"Cybersecurity refers to the practices and measures taken to protect computer systems, networks, and data from unauthorized access, attack, theft, or damage."
}

